pipeline {
 agent { node { label 'maven' } }
 environment { APP_NAMESPACE = 'ngqxba-recover' }
 stages {

 stage('Test') {
 options { timeout(time: 50, unit: 'SECONDS') }
 steps {
 dir('shopping-cart-v2') {
 sh './mvnw clean test'
 }
 }

 } //Test stage
 } //final stages end
} //pipeline end
